# Combine data

## 1. Imports

In [1]:
import pandas as pd
# import numpy as np
# import re
# import matplotlib.pyplot as plt
# import seaborn as sns

#sns.set_style('whitegrid')

## 2. Load the data

In [ ]:
RAW_CSV_PATH = "../data/raw/Datafiniti_Amazon_Consumer_Reviews_of_Amazon_Products_May19.csv"
RAW_CSV_PATH_2 = "../data/raw/Datafiniti_Amazon_Consumer_Reviews_of_Amazon_Products.csv"
RAW_CSV_PATH_3 = "../data/raw/1429_1.csv"
df = pd.read_csv(RAW_CSV_PATH)
print(df.shape)
df_2 = pd.read_csv(RAW_CSV_PATH_2)
print(df_2.shape)
df_3 = pd.read_csv(RAW_CSV_PATH_3)
print(df_3.shape)

(28332, 24)
(5000, 24)
(34660, 21)

C:\Users\kriti\AppData\Local\Temp\ipykernel_25932\2593059210.py:8: DtypeWarning: Columns (0: name, 1: reviews.didPurchase) have mixed types. Specify dtype option on import or set low_memory=False.
  df_3 = pd.read_csv(RAW_CSV_PATH_3)

In [3]:
df.head(10)

,id,dateAdded,dateUpdated,name,asins,brand,categories,primaryCategories,imageURLs,keys,...,reviews.didPurchase,reviews.doRecommend,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.username,sourceURLs
0,AVpgNzjwLJeJML43Kpxn,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...",Health & Beauty,https://images-na.ssl-images-amazon.com/images...,"amazonbasics/hl002619,amazonbasicsaaaperforman...",...,NaN,NaN,NaN,NaN,3,https://www.amazon.com/product-reviews/B00QWO9...,I order 3 of them and one of the item is bad q...,... 3 of them and one of the item is bad quali...,Byger yang,"https://www.barcodable.com/upc/841710106442,ht..."
1,AVpgNzjwLJeJML43Kpxn,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...",Health & Beauty,https://images-na.ssl-images-amazon.com/images...,"amazonbasics/hl002619,amazonbasicsaaaperforman...",...,NaN,NaN,NaN,NaN,4,https://www.amazon.com/product-reviews/B00QWO9...,Bulk is always the less expensive way to go fo...,... always the less expensive way to go for pr...,ByMG,"https://www.barcodable.com/upc/841710106442,ht..."
2,AVpgNzjwLJeJML43Kpxn,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...",Health & Beauty,https://images-na.ssl-images-amazon.com/images...,"amazonbasics/hl002619,amazonbasicsaaaperforman...",...,NaN,NaN,NaN,NaN,5,https://www.amazon.com/product-reviews/B00QWO9...,Well they are not Duracell but for the price i...,... are not Duracell but for the price i am ha...,BySharon Lambert,"https://www.barcodable.com/upc/841710106442,ht..."
3,AVpgNzjwLJeJML43Kpxn,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...",Health & Beauty,https://images-na.ssl-images-amazon.com/images...,"amazonbasics/hl002619,amazonbasicsaaaperforman...",...,NaN,NaN,NaN,NaN,5,https://www.amazon.com/product-reviews/B00QWO9...,Seem to work as well as name brand batteries a...,... as well as name brand batteries at a much ...,Bymark sexson,"https://www.barcodable.com/upc/841710106442,ht..."
4,AVpgNzjwLJeJML43Kpxn,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...",Health & Beauty,https://images-na.ssl-images-amazon.com/images...,"amazonbasics/hl002619,amazonbasicsaaaperforman...",...,NaN,NaN,NaN,NaN,5,https://www.amazon.com/product-reviews/B00QWO9...,These batteries are very long lasting the pric...,... batteries are very long lasting the price ...,Bylinda,"https://www.barcodable.com/upc/841710106442,ht..."
5,AVpgNzjwLJeJML43Kpxn,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...",Health & Beauty,https://images-na.ssl-images-amazon.com/images...,"amazonbasics/hl002619,amazonbasicsaaaperforman...",...,NaN,NaN,NaN,NaN,5,https://www.amazon.com/product-reviews/B00QWO9...,Bought a lot of batteries for Christmas and th...,... batteries for Christmas and the AmazonBasi...,ByPainter Marlow,"https://www.barcodable.com/upc/841710106442,ht..."
6,AVpgNzjwLJeJML43Kpxn,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...",Health & Beauty,https://images-na.ssl-images-amazon.com/images...,"amazonbasics/hl002619,amazonbasicsaaaperforman...",...,NaN,NaN,NaN,NaN,5,https://www.amazon.com/product-reviews/B00QWO9...,ive not had any problame with these batteries ...,... batteries have ordered them in the past be...,ByAmazon Customer,"https://www.barcodable.com/upc/841710106442,ht..."
7,AVpgNzjwLJeJML43Kpxn,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...",Health & Beauty,https://images-na.ssl-images-amazon.com/images...,"amazonbasics/hl002619,amazonbasicsaaaperforman...",...,NaN,NaN,NaN,NaN,5,https://www.amazon.com/product-reviews/B00QWO9...,Well if you are looking for cheap non-recharge...,... batteries that last quite a while then the...,ByLynn Pendegrass,"https://www.barcodable.com/upc/841710106442,ht..."
8,AVpgNzjwLJeJML43Kpxn,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...",Health & Beauty,https://images-na.ssl-images-amazon.com/images...,"amazonbasics/hl002619,amazonbasicsaaaperforman...",...,NaN,NaN,NaN,NaN,3,https://www.amazon.com/product-reviews/B00QWO9...,These do not hold the amount of high power jui...,... do not hold the amount of high power juice...,ByK.R.,"https://www.barcodable.com/upc/841710106442,ht..."
9,AVpgNzjwLJeJML43Kpxn,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...",Health & Beauty,https://images-na.ssl-images-amazon.com/images...,"amazonbasics/hl002619,amazonbasicsaaaperforman...",...,NaN,NaN,NaN,NaN,4,https://www.amazon.com/product-reviews/B00QWO9...,AmazonBasics AA AAA batteries have done well b...,... done well by me appear to have a good shel...,BySilverLane,"https://www.barcodable.com/upc/841710106442,ht..."

In [4]:
df.columns

Index(['id', 'dateAdded', 'dateUpdated', 'name', 'asins', 'brand',
       'categories', 'primaryCategories', 'imageURLs', 'keys', 'manufacturer',
       'manufacturerNumber', 'reviews.date', 'reviews.dateSeen',
       'reviews.didPurchase', 'reviews.doRecommend', 'reviews.id',
       'reviews.numHelpful', 'reviews.rating', 'reviews.sourceURLs',
       'reviews.text', 'reviews.title', 'reviews.username', 'sourceURLs'],
      dtype='str')

In [5]:
df_2.columns

Index(['id', 'dateAdded', 'dateUpdated', 'name', 'asins', 'brand',
       'categories', 'primaryCategories', 'imageURLs', 'keys', 'manufacturer',
       'manufacturerNumber', 'reviews.date', 'reviews.dateAdded',
       'reviews.dateSeen', 'reviews.doRecommend', 'reviews.id',
       'reviews.numHelpful', 'reviews.rating', 'reviews.sourceURLs',
       'reviews.text', 'reviews.title', 'reviews.username', 'sourceURLs'],
      dtype='str')

In [6]:
df_3.columns

Index(['id', 'name', 'asins', 'brand', 'categories', 'keys', 'manufacturer',
       'reviews.date', 'reviews.dateAdded', 'reviews.dateSeen',
       'reviews.didPurchase', 'reviews.doRecommend', 'reviews.id',
       'reviews.numHelpful', 'reviews.rating', 'reviews.sourceURLs',
       'reviews.text', 'reviews.title', 'reviews.userCity',
       'reviews.userProvince', 'reviews.username'],
      dtype='str')

In [7]:
for data in [df, df_2, df_3]:
    cols = data.columns.sort_values()
    
    #print(cols)#.to_list())
    print(data.isna().sum())
    print()

id                         0
dateAdded                  0
dateUpdated                0
name                       0
asins                      0
brand                      0
categories                 0
primaryCategories          0
imageURLs                  0
keys                       0
manufacturer               0
manufacturerNumber         0
reviews.date               0
reviews.dateSeen           0
reviews.didPurchase    28323
reviews.doRecommend    12246
reviews.id             28291
reviews.numHelpful     12217
reviews.rating             0
reviews.sourceURLs         0
reviews.text               0
reviews.title              0
reviews.username           5
sourceURLs                 0
dtype: int64

id                        0
dateAdded                 0
dateUpdated               0
name                      0
asins                     0
brand                     0
categories                0
primaryCategories         0
imageURLs                 0
keys                      0
manufacturer              0
manufacturerNumber        0
reviews.date              0
reviews.dateAdded      3948
reviews.dateSeen          0
reviews.doRecommend       0
reviews.id             4971
reviews.numHelpful        0
reviews.rating            0
reviews.sourceURLs        0
reviews.text              0
reviews.title            13
reviews.username          1
sourceURLs                0
dtype: int64

id                          0
name                     6760
asins                       2
brand                       0
categories                  0
keys                        0
manufacturer                0
reviews.date               39
reviews.dateAdded       10621
reviews.dateSeen            0
reviews.didPurchase     34659
reviews.doRecommend       594
reviews.id              34659
reviews.numHelpful        529
reviews.rating             33
reviews.sourceURLs          0
reviews.text                1
reviews.title               6
reviews.userCity        34660
reviews.userProvince    34660
reviews.username            7
dtype: int64

In [8]:
df_3[df_3.name.isna() == True].value_counts()

Series([], Name: count, dtype: int64)

In [9]:
imp_cols = ['asins', 'categories', 'id', 'name', 'primaryCategories', 'reviews.rating', 'reviews.text', 'reviews.title']

In [10]:
df_comb = pd.concat([df[imp_cols], df_2[imp_cols]]) # , df_3[imp_cols]
print(df_comb.shape)
df_comb.head(10)

(33332, 8)

,asins,categories,id,name,primaryCategories,reviews.rating,reviews.text,reviews.title
0,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,3,I order 3 of them and one of the item is bad q...,... 3 of them and one of the item is bad quali...
1,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,4,Bulk is always the less expensive way to go fo...,... always the less expensive way to go for pr...
2,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,Well they are not Duracell but for the price i...,... are not Duracell but for the price i am ha...
3,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,Seem to work as well as name brand batteries a...,... as well as name brand batteries at a much ...
4,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,These batteries are very long lasting the pric...,... batteries are very long lasting the price ...
5,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,Bought a lot of batteries for Christmas and th...,... batteries for Christmas and the AmazonBasi...
6,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,ive not had any problame with these batteries ...,... batteries have ordered them in the past be...
7,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,Well if you are looking for cheap non-recharge...,... batteries that last quite a while then the...
8,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,3,These do not hold the amount of high power jui...,... do not hold the amount of high power juice...
9,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,4,AmazonBasics AA AAA batteries have done well b...,... done well by me appear to have a good shel...

In [11]:
df_comb.isna().sum()

asins                 0
categories            0
id                    0
name                  0
primaryCategories     0
reviews.rating        0
reviews.text          0
reviews.title        13
dtype: int64

In [12]:
df_comb['dups'] = df_comb.duplicated(['name', 'reviews.rating', 'reviews.text'])
df_comb['dups_2'] = df_comb.duplicated()
df_comb

,asins,categories,id,name,primaryCategories,reviews.rating,reviews.text,reviews.title,dups,dups_2
0,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,3,I order 3 of them and one of the item is bad q...,... 3 of them and one of the item is bad quali...,False,False
1,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,4,Bulk is always the less expensive way to go fo...,... always the less expensive way to go for pr...,False,False
2,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,Well they are not Duracell but for the price i...,... are not Duracell but for the price i am ha...,False,False
3,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,Seem to work as well as name brand batteries a...,... as well as name brand batteries at a much ...,False,False
4,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,These batteries are very long lasting the pric...,... batteries are very long lasting the price ...,False,False
...,...,...,...,...,...,...,...,...,...,...
4995,B018Y224PY,"Tablets,Fire Tablets,Electronics,iPad & Tablet...",AVqkIdZiv8e3D1O-leaJ,"Fire Tablet with Alexa, 7"" Display, 16 GB, Mag...",Electronics,5,This is a great tablet for the price. Amazon i...,Good product,False,False
4996,B018Y224PY,"Tablets,Fire Tablets,Electronics,iPad & Tablet...",AVqkIdZiv8e3D1O-leaJ,"Fire Tablet with Alexa, 7"" Display, 16 GB, Mag...",Electronics,5,This tablet is the perfect size and so easy to...,Great Tablet,False,False
4997,B018Y224PY,"Tablets,Fire Tablets,Electronics,iPad & Tablet...",AVqkIdZiv8e3D1O-leaJ,"Fire Tablet with Alexa, 7"" Display, 16 GB, Mag...",Electronics,4,Purchased this for my son. Has room to upgrade...,Great for kids or smaller needs,False,False
4998,B018Y224PY,"Tablets,Fire Tablets,Electronics,iPad & Tablet...",AVqkIdZiv8e3D1O-leaJ,"Fire Tablet with Alexa, 7"" Display, 16 GB, Mag...",Electronics,5,I had some thoughts about getting this for a 5...,Very sturdy for a 5 year old,False,False
4999,B018Y224PY,"Tablets,Fire Tablets,Electronics,iPad & Tablet...",AVqkIdZiv8e3D1O-leaJ,"Fire Tablet with Alexa, 7"" Display, 16 GB, Mag...",Electronics,5,"this is a steal, have 8 gb model as well.This ...",great little tablet,False,False

In [13]:
df_comb[df_comb.dups == True]

,asins,categories,id,name,primaryCategories,reviews.rating,reviews.text,reviews.title,dups,dups_2
288,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,Great value,Amazon rules,True,False
581,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,great price,battery,True,False
688,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,great price,Better than stores,True,False
1069,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,Excellent,Excellent,True,False
1070,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,Excellent,Excellent,True,True
...,...,...,...,...,...,...,...,...,...,...
4789,B00REQKWGA,"Kindle E-readers,Electronics Features,Computer...",AVqVGZN9QMlgsOJE6eUZ,Kindle Oasis E-reader with Leather Charging Co...,Electronics,5,New to eBooks and researched available eReader...,Great eBooks reader,True,False
4790,B00REQKWGA,"Kindle E-readers,Electronics Features,Computer...",AVqVGZN9QMlgsOJE6eUZ,Kindle Oasis E-reader with Leather Charging Co...,Electronics,5,Was a gift to replace older one and she really...,Upgrade gift for wife,True,False
4791,B00REQKWGA,"Kindle E-readers,Electronics Features,Computer...",AVqVGZN9QMlgsOJE6eUZ,Kindle Oasis E-reader with Leather Charging Co...,Electronics,5,Very lightweight and portable with excellent b...,Works Great,True,False
4794,B00REQKWGA,"Kindle E-readers,Electronics Features,Computer...",AVqVGZN9QMlgsOJE6eUZ,Kindle Oasis E-reader with Leather Charging Co...,Electronics,5,This is my 4th kindle and is easily the best o...,Best kindle yet,True,False
4796,B00REQKWGA,"Kindle E-readers,Electronics Features,Computer...",AVqVGZN9QMlgsOJE6eUZ,Kindle Oasis E-reader with Leather Charging Co...,Electronics,5,"Wife love it, reads a lot and this is her go t...",great product,True,False

In [14]:
df_comb[['id', 'name']].value_counts()

id                    name
AVpgNzjwLJeJML43Kpxn  AmazonBasics AAA Performance Alkaline Batteries (36 Count)                               8343
AVpe7xlELJeJML43ypLz  AmazonBasics AA Performance Alkaline Batteries (48 Count) - Packaging May Vary           3728
AVqkIhxunnc1JgDc3kg_  Fire HD 8 Tablet with Alexa, 8 HD Display, 16 GB, Tangerine - with Special Offers        2443
AVqVGWQDv8e3D1O-ldFr  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi, 16 GB - Includes Special Offers, Black    2370
AVph0EeEilAPnD_x9myq  Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16 GB, Blue Kid-Proof Case                   1986
                                                                                                               ...
AV2ElNnuvKc47QAVouhY  AmazonBasics Silicone Hot Handle Cover/Holder - Red                                         1
AVzvV7FHglJLPUi8GzhD  Two Door Top Load Pet Kennel Travel Crate Dog Cat Pet Cage Carrier Box Tray 23"             1
AVpiZQ8r1cnluZ0-M3MN  AmazonBasics Nespresso Pod Storage Drawer - 50 Capsule Capacity                             1
AVpe5Q3sLJeJML43xt5X  AmazonBasics Single-Door Folding Metal Dog Crate - Large (42x28x30 Inches)                  1
AVzoFq6UvKc47QAVe9NB  Echo Dot (Previous generation)                                                              1
Name: count, Length: 80, dtype: int64

In [15]:
df_comb.groupby('categories').agg(
    cats=('name', set),
    unique_categories=('name', 'nunique')
).sort_values(
    by='unique_categories',
    ascending=False
)

,cats,unique_categories
categories,,
"Fire Tablets,Tablets,All Tablets,Amazon Tablets,Computers & Tablets","{Fire HD 8 Tablet with Alexa, 8 HD Display, 32...",4
"Amazon Echo,Smart Speakers,Electronics,Digital Device 3,Home Audio & Home Theater,Consumer Electronics,Smart Home,Smart Speakers, Hubs & Accessories,Voice Assistants,Amazon Home,Surveillance & Smart Home Electronics,Amazon,Home Audio Speakers",{Amazon Echo (2nd Generation) Smart Assistant ...,2
"E-Readers & Accessories,EBook Readers,Amazon Book Reader,Computers & Tablets,Amazon Ereaders,Kindle E-readers,E-Readers",{All-New Kindle Oasis E-reader - 7 High-Resolu...,2
"AA,AAA,Electronics Features,Health,Electronics,Health & Household,Camcorder Batteries,Camera & Photo,Batteries,Household Batteries,Accessories,Camera Batteries,Health and Beauty,Household Supplies,Batteries & Chargers,Health, Household & Baby Care,Health Personal Care",{AmazonBasics AA Performance Alkaline Batterie...,1
"Amazon Echo,Home Theater & Audio,MP3 MP4 Player Accessories,Electronics,Portable Audio,Compact Radios Stereos,Smart Hubs & Wireless Routers,Featured Brands,Smart Home & Connected Living,Home Security,Kindle Store,Electronic Components,Home Automation,Mobile Bluetooth Speakers,Home, Garage & Office,Amazon Tap,Home,Mobile Speakers,TVs & Electronics,Portable Bluetooth Speakers,Bluetooth & Wireless Speakers,Electronics Features,Frys,Speakers,Mobile,Digital Device 3,Smart Home,Home Improvement,Electronics, Tech Toys, Movies, Music,Smart Home & Home Automation Devices,Smart Hubs,MP3 Player Accessories,Home Safety & Security,Voice Assistants,Amazon Home,Alarms & Sensors,Portable Audio & Electronics,Amazon Devices,Audio,Bluetooth Speakers,MP3 Accessories,All Bluetooth & Wireless Speakers",{Amazon Tap - Alexa-Enabled Portable Bluetooth...,1
...,...,...
"eBook Readers,E-Readers & Accessories,Amazon Book Reader,Computers & Tablets,Amazon Ereaders,Kindle E-readers,E-Readers",{Kindle Oasis E-reader with Leather Charging C...,1
"eBook Readers,E-Readers & Accessories,Electronics Features,Amazon Book Reader,Computers & Tablets,Amazon Ereaders,Kindle E-readers,E-Readers",{Kindle Oasis E-reader with Leather Charging C...,1
"eBook Readers,Electronics Features,Walmart for Business,Tablets,See more Amazon Kindle Voyage (Wi-Fi),Electronics,Amazon Ereaders,Office Electronics,iPad & Tablets,Kindle E-readers,E-Readers & Accessories,All Tablets,See more Amazon Kindle Voyage 4GB, Wi-Fi 3G (Unlocked...,Amazon Book Reader,Computers & Tablets","{Kindle Voyage E-reader, 6 High-Resolution Dis...",1
"eBook Readers,Electronics Features,Walmart for Business,Tablets,See more Amazon Kindle Voyage (Wi-Fi),Electronics,Office Electronics,iPad & Tablets,Kindle E-readers,E-Readers & Accessories,All Tablets,See more Amazon Kindle Voyage 4GB, Wi-Fi 3G (Unlocked...,Computers & Tablets","{Amazon - Kindle Voyage - 6"" - 4GB - Black}",1
"eBook Readers,Fire Tablets,Electronics Features,Tablets,Amazon Tablets,College Ipads & Tablets,Electronics,Electronics Deals,College Electronics,Featured Brands,All Tablets,Computers & Tablets,Back To College,Amazon Devices,Tablets & E-Readers","{Fire HD 10 Tablet, 10.1 HD Display, Wi-Fi, 16...",1

In [16]:
df_unique = df_comb[imp_cols].drop_duplicates(subset=['name', 'reviews.rating', 'reviews.text'], ignore_index=True)
df_unique

,asins,categories,id,name,primaryCategories,reviews.rating,reviews.text,reviews.title
0,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,3,I order 3 of them and one of the item is bad q...,... 3 of them and one of the item is bad quali...
1,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,4,Bulk is always the less expensive way to go fo...,... always the less expensive way to go for pr...
2,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,Well they are not Duracell but for the price i...,... are not Duracell but for the price i am ha...
3,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,Seem to work as well as name brand batteries a...,... as well as name brand batteries at a much ...
4,"B00QWO9P0O,B00LH3DMUO","AA,AAA,Health,Electronics,Health & Household,C...",AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,Health & Beauty,5,These batteries are very long lasting the pric...,... batteries are very long lasting the price ...
...,...,...,...,...,...,...,...,...
30739,B018Y224PY,"Tablets,Fire Tablets,Electronics,iPad & Tablet...",AVqkIdZiv8e3D1O-leaJ,"Fire Tablet with Alexa, 7"" Display, 16 GB, Mag...",Electronics,5,This is a great tablet for the price. Amazon i...,Good product
30740,B018Y224PY,"Tablets,Fire Tablets,Electronics,iPad & Tablet...",AVqkIdZiv8e3D1O-leaJ,"Fire Tablet with Alexa, 7"" Display, 16 GB, Mag...",Electronics,5,This tablet is the perfect size and so easy to...,Great Tablet
30741,B018Y224PY,"Tablets,Fire Tablets,Electronics,iPad & Tablet...",AVqkIdZiv8e3D1O-leaJ,"Fire Tablet with Alexa, 7"" Display, 16 GB, Mag...",Electronics,4,Purchased this for my son. Has room to upgrade...,Great for kids or smaller needs
30742,B018Y224PY,"Tablets,Fire Tablets,Electronics,iPad & Tablet...",AVqkIdZiv8e3D1O-leaJ,"Fire Tablet with Alexa, 7"" Display, 16 GB, Mag...",Electronics,5,I had some thoughts about getting this for a 5...,Very sturdy for a 5 year old
30743,B018Y224PY,"Tablets,Fire Tablets,Electronics,iPad & Tablet...",AVqkIdZiv8e3D1O-leaJ,"Fire Tablet with Alexa, 7"" Display, 16 GB, Mag...",Electronics,5,"this is a steal, have 8 gb model as well.This ...",great little tablet

In [17]:
df_unique.shape

(30744, 8)

In [19]:
df_unique.to_csv("../data/processed/combined_data.csv", index=False)
print("Saved:", df_unique.shape)

Saved: (30744, 8)

# Notes 

- Not using 1429_1.csv dataset - because of many missing values, differnt categories and columns
- kept few important columns rather than all unused columns
- dropping duplicates based on product name, rating and review